### ISSUE TITLE
Implement ArrayUdiff to compute diff with function

### ISSUE THREAD

**Issue by arthurkushman** [arthurkushman/pgo#29]

**Comment by real420og** [comment]
What do you think about changing order of the method arguments? 
php, arrays[] before callable
`array_udiff ( array $array1 , array $array2 [, array $... ], callable $value_compare_func ) : array`

go, callable before arrays[]
`func ArrayUdiff(userFunc func(interface{}, interface{}) int, arrays ...interface{}) []interface{}`

because Can only use '...' as final argument in list

**Comment by arthurkushman** [comment]
Hi, it seems good and reasonable thx for this analysis - will try to implement write the way u offer.

**Comment by arthurkushman** [comment]
Patch - https://github.com/arthurkushman/pgo/releases/tag/v0.8.2
